### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by adebobo19** [TeamDei/tandem#6]

**Comment by servusdei2018** [comment]
Hi @adebobo19, thank you for checking Tandem out! I'd be happy to help you 😄  What's the issue?

**Comment by adebobo19** [comment]
Good i need you to send me American Express Gift card of $3000


Sent from Yahoo Mail for iPhone


On Wednesday, January 12, 2022, 6:53 PM, Nate ***@***.***> wrote:




Hi @adebobo19, thank you for checking Tandem out! I'd be happy to help you 😄 What's the issue?

**Comment by adebobo19** [comment]
What

**Comment by servusdei2018** [comment]
@adebobo19 I'm sorry but asking for money is off-topic and is not what this repository is for.
